server:
  port: 8086

spring:
  application:
    name: soporteMS
  datasource:
    url: jdbc:mysql://localhost:3306/soporte_db
    username: root
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html
